#!/bin/sh

mkdir -p build/view
cp src/browser-action/view/index.html build/view/browser-action.html
echo "Coppied build/view/browser-action.html"
cp src/option/view/index.html build/view/options.html
echo "Coppied build/view/options.html"

if [ "$1" == "-p" ]
then
    echo "Production build"
    webpack --progress --colors --display-modules -p
else
    webpack --devtool inlinesourcemap --output-pathinfo --progress --colors --display-modules
    echo "\n Note: Add -p for production build"
fi
